spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/demo?currentSchema=dev
    driver-class-name: org.postgresql.Driver
    username: demo
    password: demo
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    locations: classpath:db
    baseline-on-migrate: true
    schemas: dev,uat,prod
server:
  port: 80

logging:
  level:
    org.flywaydb: debug

management:
  endpoints:
    web:
      exposure:
        include: health,info
  health:
    probes:
      enabled: true
  endpoint:
    health:
      show-details: always
