#!/bin/sh

echo "|------------------------------------------|"
echo "| Running test before push your changes... |"
echo "|------------------------------------------|"

# Command to run all UnitTest
./gradlew clean check

# Get the result of running UnitTest [1 = FAILURE, 0 = SUCCESS]
if [ $? -ne 0 ]; then
    echo "|-----------------------------------------------|"
    echo "| Tests failed, please check and fix your code. |"
    echo "|-----------------------------------------------|"
    exit 1
else
    echo "|-------------------------------------------------------------------------|"
    echo "| Sending your changes, Thank you ! You've made this project even better! |"
    echo "|-------------------------------------------------------------------------|"
    exit 0
fi