#!/bin/sh
./gradlew test

if [ $? -ne 0 ]; then
    echo "|-------------------------------------------------------------|"
    echo "| Pre-commit hook: Test failed. Aborting commit  |"
    echo "|-------------------------------------------------------------|"
    exit 1
else
    echo "|----------------------------------------------------------------------|"
    echo "| The test was successful, now trying to commit your changes. |"
    echo "|----------------------------------------------------------------------|"
    exit 0
fi
