name: 'Run helm deploy'
description: 'Deploy helm chart to kubernetes cluster'

inputs:
  aws-region:
    description: 'aws region'
    required: false
    default: ap-southeast-2
  aws-role-arn:
    description: 'aws role ARN'
    required: false
    default: arn:aws:iam::160071257600:role/conceptual-pipeline-deployment
  cluster:
    description: 'k8s cluster'
    required: false
    default: conceptual-pipeline
  namespace:
    description: 'k8s namespace'
    required: true
    default: dev
  working-dir:
    description: 'Path to the gradle project'
    required: true


runs:
  using: "composite"
  steps:
    - name: Setup JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'adopt'
        java-version: '17'
        cache: 'gradle'
        cache-dependency-path: |
          **/*.gradle*
          **/gradle-wrapper.properties

    - name: Configure AWS Creds
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ inputs.aws-role-arn }}
        role-session-name: deploy-${{ github.run_id }}
        aws-region: ${{ inputs.aws-region }}

    - name: Update eks kubeconfig
      run: aws eks update-kubeconfig --name ${{ inputs.cluster }} --region ${{ inputs.aws-region }}
      shell: bash

    - name: Set eks namespace
      run: kubectl config set-context --current --namespace=${{ inputs.namespace }}
      shell: bash

    - name: Forward demo port to host 9090
      run: kubectl port-forward service/demo 9090:80 &
      shell: bash

    - name: Grant execute permission to gradle wrapper
      run: |
        chmod +x gradlew
      shell: bash

    - name: Run smoke test for demo service
      run: ./gradlew smokeTest -PsmokeTestBaseUrl=http://localhost:9090
      shell: bash

    - name: Upload report
      uses: actions/upload-artifact@v4
      with:
        name: smoke test report
        path: build/reports/tests/smokeTest/index.html
