name: 'Run helm deploy'
description: 'Deploy helm chart to kubernetes cluster'

inputs:
  working-dir:
    description: 'working dir'
    required: false
    default: helm
  aws-region:
    description: 'aws region'
    required: false
    default: ap-southeast-2
  aws-role-arn:
    description: 'aws role ARN'
    required: false
    default: arn:aws:iam::160071257600:role/conceptual-pipeline-deployment
  cluster:
    description: 'k8s cluster'
    required: false
    default: conceptual-pipeline
  namespace:
    description: 'k8s namespace'
    required: true
    default: dev
  image-repo:
    description: 'image repository'
    required: true
  image-tag:
    description: 'image tag'
    required: true
  db-username:
    description: 'db username'
    required: true
  db-password:
    description: 'db password'
    required: true
  db-url:
    description: 'db url'
    required: true
  db-schema:
    description: 'db schema'
    required: true

runs:
  using: "composite"
  steps:
    - name: Configure AWS Creds
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ inputs.aws-role-arn }}
        role-session-name: infra-${{ github.run_id }}
        aws-region: ${{ inputs.aws-region }}
    - name: Log in to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Update eks kubeconfig
      run: aws eks update-kubeconfig --name ${{ inputs.cluster }} --region ${{ inputs.aws-region }}
      shell: bash

    - name: Run helm deploy
      run: |
        helm upgrade demo . \
            -f "./values-${{ inputs.namespace }}.yaml" \
            --set-string image.repository="${{ inputs.image-repo }}" \
            --set-string image.tag="${{ inputs.image-tag }}" \
            --set-string configMapData.SPRING_DATASOURCE_URL="${{ inputs.db-url }}" \
            --set-string secretStringData.SPRING_DATASOURCE_USERNAME="${{ inputs.db-username }}" \
            --set-string secretStringData.SPRING_DATASOURCE_PASSWORD="${{ inputs.db-password }}" \
            --set-string configMapData.SPRING_FLYWAY_DEFAULT_SCHEMA="${{ inputs.db-schema }}" \
            --debug \
            -i \
            --atomic \
            --wait \
            -n "${{ inputs.namespace }}"
      shell: bash
      working-directory: ${{ inputs.working-dir }}
