name: 'Run helm deploy'
description: 'Deploy helm chart to kubernetes cluster'

inputs:
  working-dir:
    description: 'working dir'
    required: false
    default: helm
  aws-region:
    description: 'aws region'
    required: false
    default: ap-southeast-2
  aws-role-arn:
    description: 'aws role ARN'
    required: false
    default: arn:aws:iam::160071257600:role/conceptual-pipeline-deployment
  namespace:
    description: 'k8s namespace'
    required: false
    default: dev
  cluster:
    description: 'k8s cluster'
    required: false
    default: conceptual-pipeline
  image-repo:
    description: 'image repository'
    required: true
  image-tag:
    description: 'image tag'
    required: true

runs:
  using: "composite"
  steps:
    - name: Configure AWS Creds
      uses: aws-actions/configure-aws-credentials@v3
      with:
        role-to-assume: ${{ inputs.aws-role-arn }}
        role-session-name: deploy-${{ github.run_id }}
        aws-region: ${{ inputs.aws-region }}

    - name: update eks kubeconfig
      run: aws eks update-kubeconfig --name ${{ inputs.cluster }} --region ${{ inputs.aws-region }}
      shell: bash

    - name: Run helm deploy
      run: |
        echo "${{ secrets.SPRING_DATASOURCE_PASSWORD }}"
        echo "${{ secrets.SPRING_DATASOURCE_USERNAME }}"
        helm upgrade demo . \
            -f "./values-${{ inputs.namespace }}.yaml" \
            --set-string image.repository="${{ inputs.image-repo }}" \
            --set-string image.tag="${{ inputs.image-tag }}" \
            --debug \
            -i \
            --atomic \
            --wait \
            -n "${{ inputs.namespace }}"
      shell: bash
      working-directory: ${{ inputs.working-dir }}
