steps:
  - uses: actions/checkout@v4
  - name: Configure AWS Creds
    uses: aws-actions/configure-aws-credentials@v4
    with:
      role-to-assume: ${{ env.AWS_ROLE_ARN }}
      role-session-name: infra-${{ github.run_id }}
      aws-region: ${{ env.AWS_REGION }}
  - name: Log in to Amazon ECR
    id: login-ecr
    uses: aws-actions/amazon-ecr-login@v2
  - name: Get Latest Image tag
    id: get_image_tag
    run: |
      TAG=$(aws ecr describe-images --repository-name ${{env.AWS_ECR_REPO}} --region ${{ env.AWS_REGION }} --query 'sort_by(imageDetails[?imageTags],& imagePushedAt)[-1].imageTags[0]' --output text)
      echo "Latest image tag: $TAG"
      echo "::set-output name=image_tag::$TAG"