version: '3'

services:
  db:
    image: postgres:latest
    container_name: demo_client_db
    restart: always
    environment:
      POSTGRES_USEER: demo
      POSTGRES_PASSWORD: demo
      POSTGRES_DB: demo_client
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
