name: 'Run gradle build'
description: 'Run gradle build using gradle wrapper'

inputs:
  working-dir:
    description: 'Path to the gradle project'
    required: true

runs:
  using: "composite"
  steps:
    - name: Grant execute permission to gradle wrapper
      run: |
        chmod +x gradlew
      shell: bash
      working-directory: ${{ inputs.working-dir }}

    - name: Run Gradle build task, including unit test, integration test, and lint check
      run: ./gradlew clean build
      shell: bash
      working-directory: ${{ inputs.working-dir }}
