name: Build artifacts

on:
  push:
    branches:
      - master
    paths:
      - src/**
      - .github/workflows/ci.yaml

  pull_request:
    branches:
      - master
    paths:
      - src/**
      - .github/workflows/ci.yaml

  workflow_dispatch:

jobs:
  build_artifacts:
    name: Build artifacts
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-package: 'jdk'
          java-version: '17'
          check-latest: true

      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Run build
        uses: ./.github/actions/gradle_build
        with:
          working-dir: ./

      - name: Build docker image
        run: echo "Example, build the image here"
        shell: bash

      - name: Upload test coverage reports
        uses: codecov/codecov-action@v2
        with:
          files: ./build/reports/jacoco/test/html/index.html

