name: Continuous integration

on:
  push:
    branches:
      - master
    paths:
      - src/**
      - .github/workflows/ci.yaml

  pull_request:
    branches:
      - master
    paths:
      - src/**
      - .github/workflows/ci.yaml

  workflow_dispatch:

jobs:
  build_artifacts:
    name: Build artifacts
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '17'
          cache: 'gradle'
          cache-dependency-path: |
            **/*.gradle*
            **/gradle-wrapper.properties
      - name: Run build
        uses: ./.github/actions/gradle_build
        with:
          working-dir: ./
      - name: Build docker image
        run: docker build . --file Dockerfile --tag pipeline-demo:$(date +%s)
        shell: bash
      - name: Upload test coverage reports
        uses: codecov/codecov-action@v4
        with:
          fail_ci_if_error: true
          flags: unit_tests
          directory: ./build/reports/jacoco/test/
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

