name: OWASP Dependency Check

on:
  push:
    branches:
      - master
    paths:
      - 'src/**'
      - 'build.gradle'

jobs:
  dependency_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '17'
          cache: 'gradle'
          cache-dependency-path: |
            **/*.gradle*
            **/gradle-wrapper.properties
      - name: Cache NVD database
        uses: actions/cache@v4
        with:
          - path: |
              owasp
            key: ${{ runner.os }}-${{ hashFiles('**/*.gradle*') }}
      - name: Run the dependency check gradle task
        run: ./gradlew clean dependencyCheckAnalyze
        shell: bash
        env:
          NVD_API_KEY: ${{ secrets.NVD_API_KEY }}
